db_postgresql:
    restart: always
    image: postgres:12.1
    privileged: true
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: 'password'
        PGDATA: /var/lib/postgresql/data/pgdata //数据存储文件夹
    volumes:
        - /home/server/pg_data/data:/var/lib/postgresql/data/pgdata //将数据映射到对应的路径
