version: '3'
services: 
    web:
        image: tomcat
        container_name: tomcat1
        restart: always
        ports: 
            - "80:8080"
        volumes: 
            - "./tomcat/webapps/ROOT:/usr/local/tomcat/webapps/ROOT"
    db:
        image: mysql:5.7
        container_name: mysql1
        restart: always
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: 'password'